[build]
  publish = "public/"
  command = "yarn build"

[build.processing]
  skip_processing = true

[build.environment]
  NODE_VERSION = "22.x"

[[redirects]]
  from = "/api/*"
  to = "https://www.contributary.community/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200