version: 2
jobs:
  build:
    docker:
      - image: thegreenhouse/nodejs-dev:0.4.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Project Dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Run Linter
          command: yarn lint

      - run:
          name: Run Unit Tests
          command: export NODE_ENV=production && yarn test

      - run:
          name: Run the Build
          command: yarn build
  
  deploy_stage:
      docker:
        - image: thegreenhouse/nodejs-dev:0.4.0

      working_directory: ~/repo

      steps:
        - checkout
        - run:
            name: Deploy to Stage
            command: export RELEASE_ENV=stage && yarn install && yarn build && yarn release

  deploy_prod:
      docker:
        - image: thegreenhouse/nodejs-dev:0.4.0

      working_directory: ~/repo

      steps:
        - checkout
        - run:
            name: Deploy to Prod
            command: export RELEASE_ENV=prod && yarn install && yarn build && yarn release
           
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_stage:
          filters:
            branches:
              only: master
          requires:
            - build
      - hold:
          filters:
            branches:
              only: master
          type: approval
          requires:
           - build
      - deploy_prod:
          requires:
            - hold