version: 2
jobs:
  build:
    docker:
      - image: thegreenhouse/nodejs-dev:0.4.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Project Dependencies
          command: yarn install

      - run:
          name: Run Linter
          command: yarn lint

      - run:
          name: Run Unit Tests
          command: export NODE_ENV=production && yarn test

      - run:
          name: Build / Deploy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then

              echo "Master branch, releasing to production"
              export RELEASE_ENV=prod && yarn release

            elif [ "${CIRCLE_BRANCH}" == "develop" ]; then

              echo "Develop branch, releasing to stage"
              export RELEASE_ENV=stage && yarn release

            else

              echo "Branch undetermined, likely a CI build"
              yarn build

            fi