name: Master Integration

on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-18.04

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    strategy:
      matrix:
        node-version: [14]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Installing project dependencies
      run: |
        yarn install --frozen-lockfile
    - name: Build
      run: |
        yarn clean && yarn build
    - name: Deploy
      uses: reggionick/s3-deploy@v3
      with:
        folder: public
        bucket: ${{ secrets.S3_BUCKET }}
        bucket-region: ${{ secrets.S3_BUCKET_REGION }}
        dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        invalidation: /index.html
        delete-removed: true
        no-cache: true
        private: true